# Generated by Django 4.2.25 on 2025-11-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresso', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresso',
            name='acertos_consecutivos',
        ),
        migrations.RemoveField(
            model_name='progresso',
            name='arvores',
        ),
        migrations.AlterField(
            model_name='progresso',
            name='meta_arvores',
            field=models.PositiveIntegerField(default=25, help_text='Meta de árvores para vencer (total de perguntas).'),
        ),
    ]
