# Generated by Django 4.2.25 on 2025-11-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresso', '0002_remove_progresso_acertos_consecutivos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='fases_concluidas',
            field=models.JSONField(default=dict, help_text='Dicionário com fases concluídas: {fase_id: acertos}'),
        ),
    ]
