# Generated by Django 4.2.25 on 2025-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progresso', '0003_progresso_fases_concluidas'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresso',
            name='jogo_iniciado',
            field=models.BooleanField(default=False, help_text='Indica se o usuário já iniciou o jogo pela primeira vez'),
        ),
    ]
