# Generated by Django 4.2.25 on 2025-11-16 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pergunta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alternativa',
            options={'ordering': ['identificador'], 'verbose_name': 'Alternativa', 'verbose_name_plural': 'Alternativas'},
        ),
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['id'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='correta',
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='tipo',
        ),
        migrations.AddField(
            model_name='alternativa',
            name='identificador',
            field=models.CharField(default='a', help_text='Letra da alternativa (a, b, c, d)', max_length=1, verbose_name='Identificador'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='explicacao',
            field=models.TextField(default='', help_text='Explicação sobre por que esta é a resposta correta', verbose_name='Explicação da Resposta'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='resposta_correta_id',
            field=models.CharField(default='a', help_text='Letra da alternativa correta (a, b, c, d)', max_length=1, verbose_name='ID da Resposta Correta'),
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='texto',
            field=models.CharField(max_length=255, verbose_name='Texto da Alternativa'),
        ),
        migrations.AlterUniqueTogether(
            name='alternativa',
            unique_together={('pergunta', 'identificador')},
        ),
        migrations.RemoveField(
            model_name='alternativa',
            name='is_correta',
        ),
    ]
